{
 "title": "Amazon Timestream Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "dbName", "label": "Database Name", "query": "ec2Metrics" },
   { "name": "tableCPU", "label": "Table name for CPU", "query": "cpu" },
   { "name": "tableMEM", "label": "Table name for MEM", "query": "mem" },
   { "name": "tableSYSTEM", "label": "Table name for SYSTEM", "query": "system" },
   { "name": "tableDISK", "label": "Table name for DISK", "query": "disk" },
   { "name": "microservice", "label": "microservice", "query": "web, backoffice" }
  ]
 },
 "panels": [
  {
   "title": "CPU Average per Microservice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawQuery": "SELECT CASE WHEN microservice = 'web' THEN num_instances ELSE NULL END AS web,\n    CASE WHEN microservice = 'backoffice' THEN num_instances ELSE NULL END AS backoffice\nFROM (\n    SELECT microservice, SUM(num_instances) AS num_instances\n    FROM (\n        SELECT microservice, COUNT(DISTINCT host) as num_instances\n        FROM ${dbName}.${tableCPU}\n        WHERE $__timeFilter\n            AND measure_name = 'usage_system'\n        GROUP BY microservice\n    )\n    GROUP BY microservice\n)"
    }
   ]
  },
  {
   "title": "Hosts with Low CPU Utilization by Microservice",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawQuery": "SELECT COUNT(*) AS NumLowUtilizationHosts FROM (\n    SELECT region, microservice, host\n    FROM ${dbName}.${tableCPU}\n    WHERE $__timeFilter\n        AND measure_name = 'usage_user'\n        AND microservice = '${microservice}'\n    GROUP BY region, microservice, host\n    HAVING approx_percentile(measure_value::double, 0.9) < 20\n)"
    }
   ]
  },
  {
   "title": "Load Average by Microservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1m) AS time_bin,\n    AVG(CASE WHEN measure_name = 'load1' THEN measure_value::double ELSE NULL END) AS avg_load_short,\n    AVG(CASE WHEN measure_name = 'load5' THEN measure_value::double ELSE NULL END) AS avg_load_medium,\n    AVG(CASE WHEN measure_name = 'load15' THEN measure_value::double ELSE NULL END) AS avg_load_long\nFROM ${dbName}.${tableSYSTEM}\nWHERE measure_name IN (\n        'load1', 'load5', 'load15')\n    AND $__timeFilter\n    AND microservice = '${microservice}'\nGROUP BY BIN(time, 1m)\nORDER BY time_bin desc"
    }
   ]
  },
  {
   "title": "CPU Average per Microservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 5m) AS time_bin,\n    AVG(CASE WHEN measure_name = 'usage_user' THEN measure_value::double ELSE NULL END) AS avg_cpu_user,\n    AVG(CASE WHEN measure_name = 'usage_system' THEN measure_value::double ELSE NULL END) AS avg_cpu_system,\n    AVG(CASE WHEN measure_name = 'usage_idle' THEN measure_value::double ELSE NULL END) AS avg_cpu_idle,\n    AVG(CASE WHEN measure_name = 'usage_iowait' THEN measure_value::double ELSE NULL END) AS avg_cpu_iowait,\n    AVG(CASE WHEN measure_name = 'usage_steal' THEN measure_value::double ELSE NULL END) AS avg_cpu_steal,\n    AVG(CASE WHEN measure_name = 'usage_nice' THEN measure_value::double ELSE NULL END) AS avg_cpu_nice,\n    AVG(CASE WHEN measure_name = 'usage_guest' THEN measure_value::double ELSE NULL END) AS avg_cpu_guest,\n    AVG(CASE WHEN measure_name = 'usage_irq' THEN measure_value::double ELSE NULL END) AS avg_cpu_irq\nFROM ${dbName}.${tableCPU}\nWHERE measure_name IN (\n        'usage_user', 'usage_system', 'usage_idle', 'usage_iowait',\n        'usage_steal', 'usage_nice', 'usage_guest', 'usage_irq'\n    )\n    AND $__timeFilter\n    AND microservice = '${microservice}'\nGROUP BY BIN(time, 5m)\nORDER BY time_bin desc"
    }
   ]
  },
  {
   "title": "Memory Used Percent by Microservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, 1m) AS time_bin,\n    AVG(CASE WHEN measure_name = 'used_percent' THEN measure_value::double ELSE NULL END) AS used_percent,\n    AVG(CASE WHEN measure_name = 'available_percent' THEN measure_value::double ELSE NULL END) AS available_percent\nFROM ${dbName}.${tableMEM}\nWHERE measure_name IN (\n        'used_percent', 'available_percent')\n    AND $__timeFilter\n    AND microservice = '${microservice}'\nGROUP BY BIN(time, 1m)\nORDER BY time_bin desc"
    }
   ]
  },
  {
   "title": "Disk Used Percent by Microservice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, $__interval_ms) AS time_bin,\n    ROUND(AVG(measure_value::double), 2) AS avg_value,\n    ROUND(APPROX_PERCENTILE(measure_value::double, 0.9), 2) AS p90_value,\n    ROUND(APPROX_PERCENTILE(measure_value::double, 0.95), 2) AS p95_value,\n    ROUND(APPROX_PERCENTILE(measure_value::double, 0.99), 2) AS p99_value\nFROM ${dbName}.${tableDISK}\nWHERE $__timeFilter\n    AND measure_name = 'used_percent'\n    AND microservice = '${microservice}'\nGROUP BY BIN(time, $__interval_ms)\nORDER BY time_bin desc"
    }
   ]
  },
  {
   "title": "Measure Names SYSTEM",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "database": "\"ec2Metrics\"",
     "rawQuery": "SHOW MEASURES FROM ${dbName}.${tableSYSTEM}",
     "table": "${tableCPU}"
    }
   ]
  },
  {
   "title": "Measure Names CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "database": "\"ec2Metrics\"",
     "rawQuery": "SHOW MEASURES FROM ${dbName}.${tableCPU}",
     "table": "${tableCPU}"
    }
   ]
  },
  {
   "title": "Measure Names MEM",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "database": "\"ec2Metrics\"",
     "rawQuery": "SHOW MEASURES FROM ${dbName}.${tableMEM}",
     "table": "${tableSYSTEM}"
    }
   ]
  },
  {
   "title": "Measure Names DISK",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "database": "\"ec2Metrics\"",
     "rawQuery": "SHOW MEASURES FROM ${dbName}.${tableDISK}",
     "table": "${tableDISK}"
    }
   ]
  }
 ]
}